### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by reagar** [meagar/local27retirees.ca#16]
Would like the "from the gallery" area on the landing page to reflect the latest gallery additions.

**Comment by meagar** [comment]
This should already be the case. The last four galleries, in order of creation (**not** in the order you place them in in the admin page) are shown in this grid

**Comment by reagar** [comment]
still seems to show some of the oldest galleries, they all show jan 11 2015, must be the date the site went live? but there are much later galleries then the ones shown such as
http://www.local27retirees.ca/gallery/christmas-lunch-at-local-27

**Comment by meagar** [comment]
Oops, you're totally right. I had it ordering by date backwards instead of forwards, stupid mistake on my end.

**Comment by reagar** [comment]
looks great now
